// Windows only: the built mxbcoach.dlo carries every voice clip, in every voice, where the
// plugin looks for it (RCDATA 100 + voice * 20 + cue kind), in the format it plays. The ids are
// generated by CMakeLists.txt and computed at runtime by coachvoice::ResourceId, from two lists
// that have to stay in step; a clip embedded under an id the plugin never asks for is silence
// in the game and nothing at all in the build log. Loads the DLL as data, so nothing runs.

#include <windows.h>

#include <cstdio>
#include <vector>

#include "../src/coachvoice.h"

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: coachvoice_res_test <mxbcoach.dll>\n");
        return 2;
    }
    HMODULE mod = LoadLibraryExA(argv[1], nullptr, LOAD_LIBRARY_AS_DATAFILE | LOAD_LIBRARY_AS_IMAGE_RESOURCE);
    if (!mod) {
        std::printf("FAIL: can't load %s (%lu)\n", argv[1], GetLastError());
        return 1;
    }
    int failures = 0;
    for (int voice = 0; voice < coachvoice::kVoiceCount; ++voice) {
        const char* vname = coachvoice::kVoices[voice].key;
        for (int kind = coachcue::BRAKE; kind <= coachcue::SIT; ++kind) {
            const int id = coachvoice::ResourceId(voice, uint8_t(kind));
            HRSRC res = FindResourceA(mod, MAKEINTRESOURCEA(id), MAKEINTRESOURCEA(10));
            HGLOBAL data = res ? LoadResource(mod, res) : nullptr;
            const void* p = data ? LockResource(data) : nullptr;
            std::vector<int16_t> pcm;
            const char* name = coachvoice::kClips[coachvoice::ClipFor(uint8_t(kind))].name;
            if (!p || !coachvoice::ParseWav(static_cast<const uint8_t*>(p), SizeofResource(mod, res), pcm)) {
                std::printf("FAIL: %s clip for kind %d (%s), resource %d, missing or unreadable\n", vname, kind,
                            name, id);
                ++failures;
            } else {
                std::printf("%-6s kind %2d %-10s resource %3d %zu samples\n", vname, kind, name, id, pcm.size());
            }
        }
    }
    // The female set must stay on 101-110: those ids shipped in v0.22 and mean those clips.
    if (coachvoice::ResourceId(coachvoice::FEMALE, coachcue::BRAKE) != 101 ||
        coachvoice::ResourceId(coachvoice::FEMALE, coachcue::SIT) != 110) {
        std::printf("FAIL: the female clips have moved off the ids they shipped with\n");
        ++failures;
    }
    // And the sets must not collide, or one voice would play over the other's ids.
    if (coachvoice::ResourceId(coachvoice::MALE, coachcue::BRAKE) <=
        coachvoice::ResourceId(coachvoice::FEMALE, coachcue::SIT)) {
        std::printf("FAIL: the voice sets overlap\n");
        ++failures;
    }
    FreeLibrary(mod);
    if (failures) return 1;
    std::printf("coachvoice_res: all clips embedded, %d voices\n", coachvoice::kVoiceCount);
    return 0;
}
